name = "TrekCraft"
author = "TrekCraft"
version = "5.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e432021d17eb483354289bb3917cf8e00ec96fe9a25d2288acaae46da6e45ea"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
