name = "TrekCraft 2.0 Visitor Modpack"
author = "TrekCraft"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "940de59f47d0c4f7fd59f4d38a10765611d18d81bce64ad3926de923260667b4"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
