name = "TrekCraft 2.0 Visitor Modpack"
author = "TrekCraft"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5127b3756911afb595d17ec11fcbf4328a1198792cb3c829f161368fcfda4916"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
