name = "TrekCraft 2.0 Visitor Modpack"
author = "TrekCraft"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab9a96f33663bbd62fe319c6d3b39b73915e64123b2008a4ce5080472814dc25"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
