name = "TrekCraft 2.0 Visitor Modpack"
author = "TrekCraft"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cb6c22782d15cabf3996320af30736d25e82ba6ca0db0277a1979030eb02016"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
