name = "TrekCraft"
author = "TrekCraft"
version = "5.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9cc2a45b3f95279408b5cc68e6b69234fb771ddb269ecb93b772e65dad554dd"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
