name = "TrekCraft 2.0"
author = "TrekCraft"
version = "Fabric_1.21.1_v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaa3c3d30eea3bb030a045c72bf332fc0de88c78cb29829a8a390c848cc75878"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
