name = "TrekCraft 2.0"
author = "TrekCraft"
version = "Fabric_1.21.1_v1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa231c6218c2a068690e16c2463ebd1d55bdde0d9f63a36266e65661a5dbacac"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
