name = "TrekCraft 2.0"
author = "TrekCraft"
version = "Fabric_1.21.1_v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "155404f8d72567e20cf4e804a6311dcd34128e159fd77c745888b9a7be3695c1"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
