name = "TrekCraft 2.0"
author = "TrekCraft"
version = "Fabric_1.21.1_v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f437ecfb47f16411f7d18ca657a2060d31971372ce6e0d173761b4ec59d2a728"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
