name = "TrekCraft 2.0"
author = "TrekCraft"
version = "Fabric_1.21.1_v1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c530ba3bcaaf5249be7c9c16b555ad0d56b7aafd793c609041d79238cc0f32aa"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
