name = "TrekCraft 2.0"
author = "TrekCraft"
version = "Fabric_1.21.1_v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a73fa004d3d0f58401385fa70052a635234f479623a6fcb82d096ac35a3abfaf"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
